parameters:
    dfs.io_handler.class: eZ\Publish\Core\IO\Handler\DFS
    dfs.io_handler.metadata_handler.legacy_dfs_cluster.class: eZ\Publish\Core\IO\Handler\DFS\MetadataHandler\LegacyDFSCluster
    dfs.io_handler.binarydata_handler.dispatcher.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Dispatcher
    dfs.io_handler.binarydata_handler.filesystem.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Filesystem
    dfs.io_handler.binarydata_handler.flysystem.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Flysystem
    dfs.io_handler.binarydata_handler.dispatcher.path_based_registry.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Dispatcher\PathBasedRegistry

services:
    dfs.io_handler:
        class: %dfs.io_handler.class%
        abstract: true
        arguments:
            [ ~, ~ ]

    dfs.io_handler.metadata_handler.legacy_dfs_cluster:
        class: %dfs.io_handler.metadata_handler.legacy_dfs_cluster.class%
        abstract: true
        arguments:
            - ~

    dfs.io_handler.binarydata_handler.filesystem:
        class: %dfs.io_handler.binarydata_handler.filesystem.class%
        abstract: true
        arguments:
            - ~

    dfs.io_handler.binarydata_handler.flysystem:
        class: %dfs.io_handler.binarydata_handler.flysystem.class%
        abstract: true
        arguments:
            - ~
#
#    dfs.io_handler.binarydata_handler.dispatcher.path_based_registry:
#        class: %dfs.io_handler.binarydata_handler.dispatcher.path_basedregistry%
#        # Should be built through semantic config
#        arguments:
#            - @dfs.io_handler.binarydata_handler.filesystem
#            - {'images/': @oneup_flysystem.aws_s3}
