parameters:
    ezpublish.core.io.dfs.io_handler.class: eZ\Publish\Core\IO\Handler\DFS
    ezpublish.core.io.dfs.metadata_handler.legacy_dfs_cluster.class: eZ\Publish\Core\IO\Handler\DFS\MetadataHandler\LegacyDFSCluster
    ezpublish.core.io.dfs.binarydata_handler.dispatcher.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Dispatcher
    ezpublish.core.io.dfs.binarydata_handler.filesystem.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Filesystem
    ezpublish.core.io.dfs.binarydata_handler.flysystem.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\FlySystem
    ezpublish.core.io.dfs.binarydata_handler.dispatcher.path_based_registry.class: eZ\Publish\Core\IO\Handler\DFS\BinaryDataHandler\Dispatcher\PathBasedRegistry

services:
    ezpublish.core.io.dfs.io_handler:
        class: %ezpublish.core.io.dfs.io_handler.class%
        abstract: true
        arguments:
            [ '', ~, ~ ]

    ezpublish.core.io.dfs.metadata_handler.legacy_dfs_cluster:
        class: %ezpublish.core.io.dfs.metadata_handler.legacy_dfs_cluster.class%
        abstract: true
        arguments:
            - ~

    ezpublish.core.io.dfs.binarydata_handler.filesystem:
        class: %ezpublish.core.io.dfs.binarydata_handler.filesystem.class%
        abstract: true
        arguments:
            - ~

    ezpublish.core.io.dfs.binarydata_handler.flysystem:
        class: %ezpublish.core.io.dfs.binarydata_handler.flysystem.class%
        abstract: true
        arguments:
            - ~
#
#    dfs.io_handler.binarydata_handler.dispatcher.path_based_registry:
#        class: %dfs.io_handler.binarydata_handler.dispatcher.path_basedregistry%
#        # Should be built through semantic config
#        arguments:
#            - @dfs.io_handler.binarydata_handler.filesystem
#            - {'images/': @oneup_flysystem.aws_s3}
