parameters:
    liip_imagine.filter.configuration.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\FilterConfiguration

    ezpublish.image_alias.imagine.binary_loader.class: eZ\Bundle\EzPublishCoreBundle\Imagine\BinaryLoader
    ezpublish.image_alias.imagine.cache_resolver.class: eZ\Bundle\EzPublishCoreBundle\Imagine\IORepositoryResolver
    ezpublish.image_alias.imagine.alias_generator.class: eZ\Bundle\EzPublishCoreBundle\Imagine\AliasGenerator

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleDownOnlyFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scalewidth.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleWidthFilterLoader

services:
    ezpublish.image_alias.imagine.binary_loader:
        class: %ezpublish.image_alias.imagine.binary_loader.class%
        arguments: [@ezpublish.fieldType.ezimage.io, @liip_imagine.extension_guesser]
        tags:
            - { name: liip_imagine.binary.loader, loader: ezpublish }

    ezpublish.image_alias.imagine.cache_resolver:
        class: %ezpublish.image_alias.imagine.cache_resolver.class%
        arguments: [@ezpublish.fieldType.ezimage.io, @router.request_context, @ezpublish.config.resolver]
        tags:
            - { name: liip_imagine.cache.resolver, resolver: ezpublish }

    ezpublish.image_alias.imagine.alias_generator:
        class: %ezpublish.image_alias.imagine.alias_generator.class%
        arguments:
            - @ezpublish.image_alias.imagine.binary_loader
            - @liip_imagine.filter.manager
            - @ezpublish.image_alias.imagine.cache_resolver
            - @logger

    ezpublish.image_alias.imagine.filter.loader.scaledownonly:
        class: %ezpublish.image_alias.imagine.filter.loader.scaledownonly.class%
        calls:
            - [setInnerLoader, [@liip_imagine.filter.loader.thumbnail]]
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaledownonly" }

    ezpublish.image_alias.imagine.filter.loader.relative_scale:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, [@liip_imagine.filter.loader.relative_resize]]

    ezpublish.image_alias.imagine.filter.loader.scalewidth:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: %ezpublish.image_alias.imagine.filter.loader.scalewidth.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalewidth" }
