parameters:
    liip_imagine.filter.configuration.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\FilterConfiguration

    ezpublish.image_alias.imagine.binary_loader.class: eZ\Bundle\EzPublishCoreBundle\Imagine\BinaryLoader
    ezpublish.image_alias.imagine.cache_resolver.class: eZ\Bundle\EzPublishCoreBundle\Imagine\IORepositoryResolver
    ezpublish.image_alias.imagine.alias_generator.class: eZ\Bundle\EzPublishCoreBundle\Imagine\AliasGenerator

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width_height.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleDownOnlyFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleWidthDownOnlyFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scaledownonly.height.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleHeightDownOnlyFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scalewidth.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleWidthFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scaleheight.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleHeightFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scale.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scale_exact.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScaleExactFilterLoader
    ezpublish.image_alias.imagine.filter.loader.scale_percent.class: eZ\Bundle\EzPublishCoreBundle\Imagine\Filter\Loader\ScalePercentFilterLoader

services:
    ezpublish.image_alias.imagine.binary_loader:
        class: %ezpublish.image_alias.imagine.binary_loader.class%
        arguments: [@ezpublish.fieldType.ezimage.io, @liip_imagine.extension_guesser]
        tags:
            - { name: liip_imagine.binary.loader, loader: ezpublish }

    ezpublish.image_alias.imagine.cache_resolver:
        class: %ezpublish.image_alias.imagine.cache_resolver.class%
        arguments: [@ezpublish.fieldType.ezimage.io, @router.request_context, @ezpublish.config.resolver]
        tags:
            - { name: liip_imagine.cache.resolver, resolver: ezpublish }

    ezpublish.image_alias.imagine.alias_generator:
        class: %ezpublish.image_alias.imagine.alias_generator.class%
        arguments:
            - @ezpublish.image_alias.imagine.binary_loader
            - @liip_imagine.filter.manager
            - @ezpublish.image_alias.imagine.cache_resolver
            - @logger

    ezpublish.image_alias.imagine.filter.loader.scaledown.base:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, [@liip_imagine.filter.loader.thumbnail]]

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width_height:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: %ezpublish.image_alias.imagine.filter.loader.scaledownonly.width_height.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaledownonly" }

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: %ezpublish.image_alias.imagine.filter.loader.scaledownonly.width.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalewidthdownonly" }

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.height:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: %ezpublish.image_alias.imagine.filter.loader.scaledownonly.height.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleheightdownonly" }

    ezpublish.image_alias.imagine.filter.loader.relative_scale:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, [@liip_imagine.filter.loader.relative_resize]]

    ezpublish.image_alias.imagine.filter.loader.scalewidth:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: %ezpublish.image_alias.imagine.filter.loader.scalewidth.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalewidth" }

    ezpublish.image_alias.imagine.filter.loader.scaleheight:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: %ezpublish.image_alias.imagine.filter.loader.scaleheight.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleheight" }
            
    ezpublish.image_alias.imagine.filter.loader.scale:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: %ezpublish.image_alias.imagine.filter.loader.scale.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scale" }

    ezpublish.image_alias.imagine.filter.loader.scale_exact.base:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, [@liip_imagine.filter.loader.resize]]

    ezpublish.image_alias.imagine.filter.loader.scale_exact:
        parent: ezpublish.image_alias.imagine.filter.loader.scale_exact.base
        class: %ezpublish.image_alias.imagine.filter.loader.scale_exact.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleexact" }

    ezpublish.image_alias.imagine.filter.loader.scale_percent:
        parent: ezpublish.image_alias.imagine.filter.loader.scale_exact.base
        class: %ezpublish.image_alias.imagine.filter.loader.scale_percent.class%
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalepercent" }
